Libname ABDM "C:\Users\a\Desktop\MAITRISE HEC\SESSION_2_HIVER_2023\60105 Analyse bases de donnees mkt\DEVOIR_INDIVIDUAL\REMISE_DEVOIR";

PROC CONTENTS data=ABDM.SEGMENTATION_CONCAT;
RUN;

/*ANOVA AGE CLUSTER */
proc glm data=ABDM.SEGMENTATION_CONCAT;
class CLUSTER;
where AGE > 16 AND AGE < 117 ;
model AGE=CLUSTER;
means CLUSTER / hovtest ;
run;

/*CHI GENDER*CLUSTER */

PROC FREQ DATA=ABDM.SEGMENTATION_CONCAT;
TABLE GENDER*CLUSTER / CHISQ EXPECTED DEVIATION NOROW NOCOL NOPERCENT;
RUN;


/*CHI PROV*CLUSTER */
PROC FREQ DATA=ABDM.SEGMENTATION_CONCAT;
TABLE PROV*CLUSTER / CHISQ EXPECTED DEVIATION NOROW NOCOL NOPERCENT;
RUN;
